language: android

android:
   components:
     - platform-tools
     - tools
     - build-tools-28.0.3
     - android-28
     - extra-android-m2repository

sudo: required

before_install: chmod +x ./gradlew
install: ./gradlew assemble --stacktrace
script: ./gradlew check